# Basic config
baseURL = "http://localhost:1313"  # Update this to your actual site URL after deployment
theme = "hugo-bearcub"
copyright = "Alwin Rajkumar (CC BY 4.0)"
defaultContentLanguage = "en"


[[menu.main]]
    name = "Blog"
    url = "https://alwnraj.github.io/newblog/blog/"
    weight = 2


# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Setup syntax highlighting without inline styles
[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false  # Setting to false allows for better styling control

# Multilingual mode config
[languages]
  [languages.en]
    title = "Alwin Cub"
    languageName = "en-US 🇺🇸"
    languageCode = "en-US"
    contentDir = "content"
    [languages.en.params]
      madeWith = "Made with [Bear Cub](https://github.com/clente/hugo-bearcub)"



[params]
  # The description of your website
  description = "Alwin Cub Demo"

  # The path to your favicon
  favicon = "images/favicon.png"

  # Images for link previews
  images = ["images/share.webp"]

  # Title used for Open Graph structured data
  title = "Bear Cub"

  # Date format
  dateFormat = "2006-01-02"

  # Hide untranslated pages in multilingual setups
  hideUntranslated = false

  # CSS styles for the theme
  themeStyle = "original"  # Change to "herman" if you prefer a different style

  # Dynamically generated social cards
  generateSocialCard = true

  # Social media metadata
  [params.social]
    twitter = "example"  # Twitter handle (without '@')

  # Author metadata
  [params.author]
    name = "John Doe"  # Your name as shown in the RSS feed metadata
    email = "me@example.com"  # Added to the footer for replies

# Additional Optional Settings
[params.analytics]
  googleAnalytics = "UA-XXXXX-Y"  # Add your Google Analytics tracking ID here if desired
